[package]
name = "json-core"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = "^4.5"
jsonschema = "0.30"
rayon = "1.5"
serde_json = "1.0"
sha2 = "0.10"
self_update = "0.42"
walkdir = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
