name: Release Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: json-core.exe
            asset_name: json-core-windows-x64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: json-core
            asset_name: json-core-linux-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: json-core
            asset_name: json-core-macos-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: json-core
            asset_name: json-core-macos-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare asset
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release/${{ matrix.asset_name }}
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            chmod +x release/${{ matrix.asset_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: release/${{ matrix.asset_name }}
          if-no-files-found: error

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/json-core-windows-x64.exe/json-core-windows-x64.exe
            artifacts/json-core-linux-x64/json-core-linux-x64
            artifacts/json-core-macos-x64/json-core-macos-x64
            artifacts/json-core-macos-arm64/json-core-macos-arm64
